### ISSUE TITLE
GCC 5 Issue

### ISSUE THREAD

**Issue by f3n9** [libyal/libuna#2] opened 2015-04-23 10:22 UTC
The default C standard in GCC 5.x is GNU11.
So the macro 'LIBUNA_EXTERN' in libuna_extern.h should be set to 'extern' otherwise libtool would fail to link with libuna library.
Setting -std=gnu89 in CFLAGS might also work, but I didn't give it a try.
See https://gcc.gnu.org/gcc-5/porting_to.html .

**Comment by joachimmetz** [comment] 2015-04-23 17:44
Thx already had an action item to have a look at gcc5. Will try if time permits.

**Comment by joachimmetz** [comment] 2015-04-23 21:07
Which platform are you using? It seems to works just fine with ggc 5.0.1 on Fedora 22 beta.

**Comment by f3n9** [comment] 2015-04-23 22:01
libuna itself doesnt have issue to compile on f22/gcc5.0.1, but libtool would fail with 'undefined reference' error while linking it with other components of libfvde.
I'm also using f22beta with gcc 5.0.1  .

**Comment by joachimmetz** [comment] 2015-05-10 13:48
> So the macro 'LIBUNA_EXTERN' in libuna_extern.h should be set to 'extern'
> otherwise libtool would fail to link with libuna library.

It is set, just follow the code:

```
#include <libuna/extern.h>
```

https://github.com/libyal/libuna/blob/master/libuna/libuna_extern.h#L38

```
#define LIBUNA_EXTERN extern
```

https://github.com/libyal/libuna/blob/master/include/libuna/extern.h#L38

The following is only used by local (or in-package) usage:

```
#define LIBUNA_EXTERN   /* extern */
```

https://github.com/libyal/libuna/blob/master/libuna/libuna_extern.h#L44

**Comment by joachimmetz** [comment] 2015-05-10 13:58
The cause is more likely to be the inline definitions. Though I can still not reproduce it, libfvde with a stand-alone libuna compiles and links just fine for me.

**Comment by joachimmetz** [comment] 2015-05-10 14:10
How did you get the source from the releases package or from git?

**Comment by joachimmetz** [comment] 2015-05-10 14:14
Also what does the following command tell you regarding the missing functions:

```
nm -D libuna/.libs/libuna.so
```

**Comment by gvanem** [comment] 2015-12-15 23:10
> The following is only used by local (or in-package) usage:
>
> #define LIBUNA_EXTERN   /* extern */

Then why is MSVC treated specially:
```
#elif defined( _MSC_VER )
#define LIBUNA_EXTERN   extern

#else
#define LIBUNA_EXTERN   /* extern */

#endif
```

And what about Borland?

I tried building your libs (static only for MingW+MSVC) since I was interested in `libevtx`. But the dependencies are a big bole of tangled spaghetti. I got the impression I needed to add `HAVE_LOCAL_LIBUNA` in my `config.h`, but that causes a link failure:
```
gcc -m32 -o  una_test_base16_stream_copy_from.exe  una_test_base16_stream_copy_from.o ../libuna.a ../libcerror.a
una_test_base16_stream_copy_from.o: In function `una_test_base16_stream_copy_from_byte_stream':
tests/una_test_base16_stream_copy_from.c:115: undefined reference to `libuna_error_backtrace_fprint'
una_test_base16_stream_copy_from.c:119: undefined reference to `libuna_error_free'
una_test_base16_stream_copy_from.c:74: undefined reference to `libuna_error_free'
...
```
Which is evident from `libuna_error.c` (all functions are inside `#if !defined (HAVE_LOCAL_LIBUNA`)) What could I do?

**Comment by joachimmetz** [comment] 2015-12-16 06:15
@gvanem why are you hijacking a completely different issue?

> But the dependencies are a big bole of tangled spaghetti.

If you want to help me why are you acting like this? 

> I tried building your libs (static only for MingW+MSVC) since I was interested in libevtx.

Open a new

**Comment by joachimmetz** [comment] 2016-04-20 13:02
Should be fixed now.

**Closed as completed** 2016-04-20 13:02 UTC
Labels: question
